# Generated by Django 5.0.4 on 2024-05-16 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editores',
            },
        ),
        migrations.AddField(
            model_name='juego',
            name='editores',
            field=models.ManyToManyField(related_name='juegos', to='juegos.editor'),
        ),
    ]
